// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZX6f79-Evp7RtqTl-PAoMP82X2Yg85-8',
    appId: '1:595027597427:web:02e8186fb0904728727206',
    messagingSenderId: '595027597427',
    projectId: 'login-app-6ba0c',
    authDomain: 'login-app-6ba0c.firebaseapp.com',
    storageBucket: 'login-app-6ba0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9806ZKoF8Z6sDdovfsvwyYNTYTNZk7A',
    appId: '1:595027597427:android:414b06e93841615e727206',
    messagingSenderId: '595027597427',
    projectId: 'login-app-6ba0c',
    storageBucket: 'login-app-6ba0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3YmA-rqu1XQPkbu1cnNmZ1d_R_qigVPo',
    appId: '1:595027597427:ios:8157fadc5a31aa0a727206',
    messagingSenderId: '595027597427',
    projectId: 'login-app-6ba0c',
    storageBucket: 'login-app-6ba0c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3YmA-rqu1XQPkbu1cnNmZ1d_R_qigVPo',
    appId: '1:595027597427:ios:8157fadc5a31aa0a727206',
    messagingSenderId: '595027597427',
    projectId: 'login-app-6ba0c',
    storageBucket: 'login-app-6ba0c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZX6f79-Evp7RtqTl-PAoMP82X2Yg85-8',
    appId: '1:595027597427:web:6949b4049a2ec04a727206',
    messagingSenderId: '595027597427',
    projectId: 'login-app-6ba0c',
    authDomain: 'login-app-6ba0c.firebaseapp.com',
    storageBucket: 'login-app-6ba0c.firebasestorage.app',
  );
}
