// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YRBeSlI1XGp2u9ij-YleB2zdPyoYcJM',
    appId: '1:381531665070:web:078d23dd28bdfb20d5333f',
    messagingSenderId: '381531665070',
    projectId: 'firestore-d4fcf',
    authDomain: 'firestore-d4fcf.firebaseapp.com',
    storageBucket: 'firestore-d4fcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJRLwseEu6okwTj38g9BeU0X5xXtPoL8o',
    appId: '1:381531665070:android:225d7e56f4936daad5333f',
    messagingSenderId: '381531665070',
    projectId: 'firestore-d4fcf',
    storageBucket: 'firestore-d4fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7GZb_FdPcdPh6qHejPeESO4MWs4DLOU',
    appId: '1:381531665070:ios:6aca5d8b8cce6c46d5333f',
    messagingSenderId: '381531665070',
    projectId: 'firestore-d4fcf',
    storageBucket: 'firestore-d4fcf.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7GZb_FdPcdPh6qHejPeESO4MWs4DLOU',
    appId: '1:381531665070:ios:6aca5d8b8cce6c46d5333f',
    messagingSenderId: '381531665070',
    projectId: 'firestore-d4fcf',
    storageBucket: 'firestore-d4fcf.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1YRBeSlI1XGp2u9ij-YleB2zdPyoYcJM',
    appId: '1:381531665070:web:4beac40a0980a110d5333f',
    messagingSenderId: '381531665070',
    projectId: 'firestore-d4fcf',
    authDomain: 'firestore-d4fcf.firebaseapp.com',
    storageBucket: 'firestore-d4fcf.firebasestorage.app',
  );
}
